spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${{secrets.AWS_RDS_URL}}
    username: ${{secrets.AWS_RDS_USERNAME}}
    password: ${{secrets.AWS_RDS_PASSWORD}}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    include: API-KEY
jwt:
  secret: ${{secrets.JWT_TOKEN_SECRET}}

server:
  port: 8080
